replicaCount: 1
image:
  repository: ghcr.io/amyjeanes/homeautomation.web
  tag: latest
  pullPolicy: Always
ingress:
  host: ""
resources:
  requests:
    memory: 75Mi
    cpu: 10m
  limits:
    memory: 75Mi
env:
  secret:
    Key: ""
    Mqtt__Password: ""
  normal:
    Mqtt__Server: ""
    Mqtt__Username: ""